// components/SettingsScreen/SettingsModal.styles.ts
import { Dimensions, StyleSheet } from 'react-native';

const { width, height } = Dimensions.get('window');

export const settingsModalStyles = StyleSheet.create({
    modalOverlay: {
        flex: 1,
        backgroundColor: 'rgba(0, 0, 0, 0.85)',
        justifyContent: 'center',
        alignItems: 'center',
        padding: 20,
    },
    modalContent: {
        backgroundColor: '#0a0a15',
        borderRadius: 16,
        padding: 24,
        width: '100%',
        height: '80%',
        borderWidth: 1,
        borderColor: 'rgba(0, 255, 255, 0.2)',
        shadowColor: '#00FFFF',
        shadowOffset: {
            width: 0,
            height: 0,
        },
        shadowOpacity: 0.2,
        shadowRadius: 8,
        elevation: 6,
    },
    title: {
        fontSize: 24,
        color: '#FFFFFF',
        fontWeight: '600',
        textAlign: 'center',
        marginBottom: 20,
        letterSpacing: 1,
    },
    tabsContainer: {
        flexDirection: 'row',
        marginBottom: 20,
        backgroundColor: 'transparent',
        borderRadius: 10,
        padding: 0,
        borderBottomWidth: 1,
        borderBottomColor: 'rgba(0, 255, 255, 0.1)',
    },
    tabButton: {
        flex: 1,
        backgroundColor: 'transparent',
        paddingVertical: 14,
        borderRadius: 0,
        marginHorizontal: 0,
        borderBottomWidth: 2,
        borderBottomColor: 'transparent',
    },
    tabButtonActive: {
        flex: 1,
        backgroundColor: 'transparent',
        paddingVertical: 14,
        borderRadius: 0,
        marginHorizontal: 0,
        borderBottomWidth: 2,
        borderBottomColor: '#00FFFF',
    },
    tabButtonText: {
        color: 'rgba(255, 255, 255, 0.5)',
        fontSize: 15,
        fontWeight: '500',
        textAlign: 'center',
        letterSpacing: 0.5,
    },
    tabButtonTextActive: {
        color: '#00FFFF',
        fontSize: 15,
        fontWeight: '600',
        textAlign: 'center',
        letterSpacing: 0.5,
    },
    list: {
        flex: 1,
        marginBottom: 10,
    },
    sectionHeader: {
        backgroundColor: 'rgba(0, 255, 255, 0.08)',
        padding: 14,
        borderRadius: 10,
        marginVertical: 6,
        borderLeftWidth: 3,
        borderLeftColor: 'rgba(0, 255, 255, 0.5)',
    },
    sectionTitle: {
        fontSize: 16,
        color: '#FFFFFF',
        fontWeight: '600',
        textAlign: 'left',
        letterSpacing: 0.5,
    },
    statsRow: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        paddingVertical: 12,
        paddingHorizontal: 8,
        borderBottomWidth: 1,
        borderBottomColor: 'rgba(255, 255, 255, 0.05)',
    },
    statLabel: {
        fontSize: 15,
        color: 'rgba(255, 255, 255, 0.9)',
        flex: 1,
        letterSpacing: 0.3,
    },
    statValue: {
        fontSize: 15,
        color: '#00FFFF',
        fontWeight: '500',
        letterSpacing: 0.3,
    },
    closeButton: {
        backgroundColor: 'transparent',
        borderWidth: 1,
        borderColor: 'rgba(255, 255, 255, 0.3)',
        paddingVertical: 14,
        borderRadius: 10,
        marginTop: 10,
        shadowColor: '#00FFFF',
        shadowOffset: {
            width: 0,
            height: 0,
        },
        shadowOpacity: 0.1,
        shadowRadius: 4,
        elevation: 3,
    },
    closeButtonText: {
        color: 'rgba(255, 255, 255, 0.8)',
        fontSize: 16,
        fontWeight: '500',
        textAlign: 'center',
        letterSpacing: 0.5,
    },
});