// app/game.styles.ts
import { Dimensions, Platform, StyleSheet } from 'react-native';

const { width: screenWidth, height: screenHeight } = Dimensions.get('window');

export const gameStyles = StyleSheet.create({
    container: {
        flex: 1,
    },
    fullScreen: {
        flex: 1,
        width: screenWidth,
        height: screenHeight,
        position: 'relative',
    },
    scoreText: {
        position: 'absolute',
        top: Platform.OS === 'ios' ? 60 : 30,
        width: '100%',
        textAlign: 'center',
        fontSize: 30,
        color: 'white',
        zIndex: 100,
    },
    tapToStartContainer: {
        position: 'absolute',
        top: 0,
        left: 0,
        right: 0,
        bottom: 0,
        justifyContent: 'center',
        alignItems: 'center',
        zIndex: 200,
    },
    tapToStart: {
        fontSize: 25,
        color: 'yellow',
        textAlign: 'center',
        backgroundColor: 'rgba(0, 0, 0, 0.7)',
        padding: 20,
        borderRadius: 10,
    },
    gameOverContainer: {
        position: 'absolute',
        top: 0,
        left: 0,
        right: 0,
        bottom: 0,
        justifyContent: 'center',
        alignItems: 'center',
        backgroundColor: 'rgba(0, 0, 0, 0.8)',
        zIndex: 300,
    },
    gameOverText: {
        fontSize: 40,
        color: 'red',
        fontWeight: 'bold',
        marginBottom: 20,
        textAlign: 'center',
    },
    countdownText: {
        position: 'absolute',
        top: screenHeight / 2 - 20,
        width: '100%',
        textAlign: 'center',
        fontSize: 80,
        color: 'white',
        fontWeight: 'bold',
        zIndex: 200,
    },
    restartButton: {
        fontSize: 30,
        color: '#00FFFF',
        fontWeight: 'bold',
        textAlign: 'center',
    },
    restartButtonContainer: {
        padding: 20,
        backgroundColor: 'rgba(0, 0, 0, 0.8)',
        borderRadius: 10,
        marginTop: 20,
        borderWidth: 2,
        borderColor: '#00FFFF',
    },
    finalScoreText: {
        fontSize: 25,
        color: 'yellow',
        fontWeight: 'bold',
        marginBottom: 10,
        textAlign: 'center',
    },
    highScoreText: {
        fontSize: 20,
        color: '#00FF00',
        fontWeight: 'bold',
        marginBottom: 20,
        textAlign: 'center',
    },
    gameArea: {
        flex: 1,
        width: '100%',
        height: '100%',
    },
    loadingText: {
        fontSize: 24,
        color: '#00FFFF',
        fontWeight: 'bold',
        textAlign: 'center',
        marginTop: 20,
        paddingTop: Platform.OS === 'ios' ? 40 : 20,
    },
});